import json
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "skills" / "dementia-causal-cohort-auditor" / "scripts" / "plan_nacc_cohort_build.py"
DESIGN_PACKET = ROOT / "examples" / "outputs" / "nacc_design_packet"
AGGREGATE = ROOT / "examples" / "outputs" / "nacc_aggregate_validation"


class NaccDesignToCodePlannerTest(unittest.TestCase):
    def test_planner_generates_blocked_plan_without_cohort_outputs(self) -> None:
        with tempfile.TemporaryDirectory() as tmpdir:
            output_dir = Path(tmpdir) / "plan"
            result = subprocess.run(
                [
                    sys.executable,
                    str(SCRIPT),
                    "--design-packet-dir",
                    str(DESIGN_PACKET),
                    "--aggregate-validation-dir",
                    str(AGGREGATE),
                    "--output-dir",
                    str(output_dir),
                ],
                capture_output=True,
                text=True,
                check=False,
            )
            self.assertEqual("", result.stderr)
            self.assertEqual(0, result.returncode)

            expected = [
                "build_plan.md",
                "build_pseudocode.py",
                "implementation_checklist.md",
                "validation_test_plan.md",
                "planner_manifest.json",
            ]
            for filename in expected:
                self.assertTrue((output_dir / filename).exists(), filename)

            forbidden = ["cohort.csv", "feature_table.csv", "cohort_index.csv"]
            for filename in forbidden:
                self.assertFalse((output_dir / filename).exists(), filename)

            manifest = json.loads((output_dir / "planner_manifest.json").read_text(encoding="utf-8"))
            self.assertEqual("0.14", manifest["schema_version"])
            self.assertFalse(manifest["patient_level_data_read"])
            self.assertFalse(manifest["cohort_construction_performed"])
            self.assertFalse(manifest["ready_for_executable_cohort_build"])
            self.assertEqual("blocked_planner_draft", manifest["planner_status"])

            plan = (output_dir / "build_plan.md").read_text(encoding="utf-8")
            self.assertIn("Ready for executable cohort build: false", plan)
            self.assertIn("Mapping contains unresolved selected_field entries", plan)
            self.assertIn("select_index_visit", plan)

            pseudocode = (output_dir / "build_pseudocode.py").read_text(encoding="utf-8")
            self.assertIn("Generated by v0.14 design-to-code planner", pseudocode)
            self.assertIn("derive_prediction_outcome", pseudocode)


if __name__ == "__main__":
    unittest.main()
