#!/usr/bin/env python
"""Pseudocode for future NACC cohort construction.

Generated by v0.14 design-to-code planner. This file is intentionally not a
ready-to-run cohort builder.
"""


def main(config):
    assert config.design_status in {"approved", "human_approved", "design_approved"}
    assert config.mapping_all_selected_fields_confirmed is True
    assert config.real_data_execution_approved_by_user is True

    core = load_selected_nacc_tables(config)
    core = normalize_missing_codes(core, config.dictionary_rules)
    core = construct_visit_date(core)

    stage_counts = []
    stage_counts.append(count_stage("all_core_clinical_records", core))

    valid_rows = require_valid_participant_and_visit(core)
    stage_counts.append(count_stage("valid_participant_id_and_visit", valid_rows))

    index_visits = select_index_visit(valid_rows, config.time_zero_rule)
    index_visits = apply_age_rule(index_visits, config.age_rule)
    stage_counts.append(count_stage("age_eligible_if_required", index_visits))

    index_visits = apply_baseline_dementia_free_rule(
        valid_rows,
        index_visits,
        config.baseline_window,
        config.baseline_dementia_rule,
    )
    stage_counts.append(count_stage("dementia_free_baseline_if_required", index_visits))

    index_visits = apply_apoe_rule(index_visits, config.apoe_missingness_rule)
    stage_counts.append(count_stage("apoe_available_if_required", index_visits))

    outcomes = derive_prediction_outcome(
        valid_rows,
        index_visits,
        config.outcome_definition,
        config.follow_up_window,
    )
    assert all_outcomes_after_time_zero(outcomes, index_visits)

    features = build_feature_table(valid_rows, index_visits, config.predictor_window)
    assert no_post_index_predictors(features, index_visits)

    package = assemble_cohort_package(index_visits, features, outcomes)
    write_attrition_table(stage_counts)
    write_data_quality_report(run_data_quality_checks(package, valid_rows, config))
    write_leakage_report(run_leakage_checks(package, valid_rows, config))
    write_reproducibility_manifest(config)
    return package
